version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    working_dir: /var/www/src
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src

  web:
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./.docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./.docker/web/ssl
        target: /etc/nginx/ssl
      - type: bind
        source: ./src
        target: /var/www/src

  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: ./.docker/db/my.conf
        target: /etc/my.conf
      - type: bind
        source: ./.docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    depends_on:
      - app

volumes:
  db:
